### ISSUE TITLE
Merge with mine?

### ISSUE THREAD

**Issue by bebraw** [valor-software/prismjs-loader#1]
Hi,

I wrote a [prism loader](https://github.com/survivejs/react-demos/blob/master/loaders/prism.js) before I noticed you had written one. Maybe you could take some of the best ideas from there and merge them to yours?

The lookup relies on [prism-languages](https://www.npmjs.com/package/prism-languages). That's package has been generated based on prism to make it easy to consume the definitions through Node. Hopefully this package becomes obsolete at some point. It works quite well for now, though.

**Comment by valorkin** [comment]
@bebraw why not to help prismjs with updating language definitions instead of creating https://github.com/survivejs/prism-languages ? I suppose he will appreciate it a lot,
just wrap definitions

**Comment by valorkin** [comment]
@bebraw and how you loader works without `return 'module.exports = ' + JSON.stringify(this.value);` ?
took a look at your module, error in loader are configuration\developer errors, and should be thrown, not logged to console

**Comment by bebraw** [comment]
> @bebraw why not to help prismjs with updating language definitions instead of creating https://github.com/survivejs/prism-languages ? I suppose he will appreciate it a lot,
> just wrap definitions

Sure. See https://github.com/PrismJS/prism/issues/768 and https://github.com/PrismJS/prism/pull/578 . Once the PR gets in, I suppose I can ditch prism-languages.

> @bebraw and how you loader works without return 'module.exports = ' + JSON.stringify(this.value); ?

I pass it through `html-loader`. It's not meant to be used a standalone.

> took a look at your module, error in loader are configuration\developer errors, and should be thrown, not logged to console

Great point! I'll change that.

**Comment by bebraw** [comment]
Time to close this.

FYI, Prism provides sane language definitions for Node now. You can do just `require('prismjs').languages` to access them.
